### ISSUE TITLE
[DEPR]: Remove enhanced staff grader demo code

### ISSUE THREAD

**Issue by KristinAoki** [edx/edx-ora2#2250]
### Proposal Date

2024-11-18

### Target Ticket Acceptance Date

2024-12-02

### Earliest Open edX Named Release Without This Functionality

Teak - 2025-04

### Rationale

This proposal is to support the deprecation of the `openresponseassessment.enhanced_staff_grader` waffle flag. When the enhanced staff grader is not enabled, the user is shown a link to demo the enhanced staff grader, but they are not able to actually grade their content. After two full releases, it makes sense to remove the demo functionality and default to the enhanced staff grader by default. The legacy version of the staff grader will remain because the current enhanced staff grader is not compatible with team assignments.

### Removal

Removal of waffle flag:

- [ ] https://github.com/openedx/edx-ora2/blob/master/openassessment/xblock/config_mixin.py#L16
- [ ] https://github.com/openedx/edx-ora2/blob/master/openassessment/xblock/config_mixin.py#L27
- [ ] https://github.com/openedx/edx-ora2/blob/master/openassessment/xblock/config_mixin.py#L156-#L168

Remove references to waffle flag:

- [ ] https://github.com/openedx/edx-ora2/blob/master/openassessment/xblock/openassessmentblock.py#L722
- [ ] https://github.com/openedx/edx-ora2/blob/master/openassessment/xblock/staff_area_mixin.py#L142-L148

### Replacement

Update waffle flag references:
https://github.com/openedx/edx-ora2/blob/master/openassessment/templates/legacy/staff_area/oa_staff_area.html#L15-#L23
```
{% if not team_assignment and enhanced_staff_grader_url %}
   <a href="{{enhanced_staff_grader_url}}" class="ui-staff__button button-enhanced-staff-grader" aria-expanded="false">{% trans "Grade Available Responses" %} <span class="icon fa fa-external-link" aria-hidden="true"></span></a>
{% else %}
    <button class="ui-staff__button button-staff-grading" aria-expanded="false" data-panel="openassessment__staff-grading">{% trans "Grade Available Responses" %}</button>
{% endif %}
```

### Task List
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/edx-platform/issues/35870
```
